// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCs_Rest_Api.Data;

#nullable disable

namespace PCs_Rest_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PCs_Rest_Api.Entities.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Component", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "RAM0000001",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 1,
                            Description = "8GB DDR4 3200MHz",
                            Name = "Corsair Vengeance"
                        },
                        new
                        {
                            Code = "SSD0000001",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 2,
                            Description = "500GB NVMe M.2 PCIe Gen3",
                            Name = "Samsung SSD"
                        },
                        new
                        {
                            Code = "GPU0000001",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 3,
                            Description = "4GB VRAM",
                            Name = "RTX 4080 Super"
                        },
                        new
                        {
                            Code = "CPU0000001",
                            ComponentManufacturerId = 4,
                            ComponentTypeId = 4,
                            Description = "4 Cores 8 Threads 4.20 GHz ",
                            Name = "Intel Core i5"
                        });
                });

            modelBuilder.Entity("PCs_Rest_Api.Entities.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CRU",
                            FoundationDate = new DateOnly(1996, 1, 1),
                            FullName = "Crucial Technology"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "SND",
                            FoundationDate = new DateOnly(1938, 3, 1),
                            FullName = "Samsung Electronics"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVD",
                            FoundationDate = new DateOnly(1938, 4, 5),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "INT",
                            FoundationDate = new DateOnly(1968, 7, 18),
                            FullName = "Intel Corporation"
                        });
                });

            modelBuilder.Entity("PCs_Rest_Api.Entities.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "RAM",
                            Name = "Memory (RAM)"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "SSD",
                            Name = "Solid State Drive"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        });
                });

            modelBuilder.Entity("PCs_Rest_Api.Entities.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasMaxLength(5)
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Computer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Asus TUF Gaming",
                            Stock = 10,
                            Warranty = 1,
                            Weight = 2.2000000476837158
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dell Alienware",
                            Stock = 5,
                            Warranty = 2,
                            Weight = 2.5
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lenovo ThinkPad",
                            Stock = 12,
                            Warranty = 3,
                            Weight = 2.7000000476837158
                        });
                });

            modelBuilder.Entity("PCs_Rest_Api.Entities.ComputerComponent", b =>
                {
                    b.Property<int>("ComputerId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("ComputerId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("ComputerComponent", (string)null);

                    b.HasData(
                        new
                        {
                            ComputerId = 1,
                            ComponentCode = "RAM0000001",
                            Amount = 4
                        },
                        new
                        {
                            ComputerId = 1,
                            ComponentCode = "SSD0000001",
                            Amount = 1
                        },
                        new
                        {
                            ComputerId = 1,
                            ComponentCode = "GPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            ComputerId = 1,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            ComputerId = 2,
                            ComponentCode = "RAM0000001",
                            Amount = 2
                        },
                        new
                        {
                            ComputerId = 2,
                            ComponentCode = "SSD0000001",
                            Amount = 1
                        },
                        new
                        {
                            ComputerId = 2,
                            ComponentCode = "GPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            ComputerId = 2,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            ComputerId = 3,
                            ComponentCode = "RAM0000001",
                            Amount = 4
                        },
                        new
                        {
                            ComputerId = 3,
                            ComponentCode = "SSD0000001",
                            Amount = 1
                        },
                        new
                        {
                            ComputerId = 3,
                            ComponentCode = "GPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            ComputerId = 3,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("PCs_Rest_Api.Entities.Component", b =>
                {
                    b.HasOne("PCs_Rest_Api.Entities.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCs_Rest_Api.Entities.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("PCs_Rest_Api.Entities.ComputerComponent", b =>
                {
                    b.HasOne("PCs_Rest_Api.Entities.Component", "Component")
                        .WithMany("ComputerComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PCs_Rest_Api.Entities.Computer", "Computer")
                        .WithMany("ComputerComponents")
                        .HasForeignKey("ComputerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Computer");
                });

            modelBuilder.Entity("PCs_Rest_Api.Entities.Component", b =>
                {
                    b.Navigation("ComputerComponents");
                });

            modelBuilder.Entity("PCs_Rest_Api.Entities.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PCs_Rest_Api.Entities.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PCs_Rest_Api.Entities.Computer", b =>
                {
                    b.Navigation("ComputerComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
